export enum CoatType {
	SHORT = "SHORT",
	MEDIUM = "MEDIUM",
	LONG = "LONG",
}
export enum AppointmentStatus {
	SCHEDULED = "SCHEDULED",
	CONFIRMED = "CONFIRMED",
	IN_PROGRESS = "IN_PROGRESS",
	COMPLETED = "COMPLETED",
	NO_SHOW = "NO_SHOW",
	CANCELED = "CANCELED",
}
